#creating tables in SQL

SQL> --ProdID ( PK )
SQL> --ProdName ( Not Null )
SQL> --Qty ( Chk > 0 )
SQL> --Description
SQL> 
SQL> 
SQL> --ORDERS
SQL> 
SQL> --ProdID ( FK from products )
SQL> --OrderID ( PK )
SQL> --Qty_sold ( chk > 0 )
SQL> --Price 
SQL> --Order_Date

CREATE TABLE PRODUCTS( 
PRODID NUMBER(20) PRIMARY KEY,
PRODNAME VARCHAR(30) NOT NULL,
QTY NUMBER(10) CHECK(QTY >0),
DESCRIPTION VARCHAR(30));

CREATE TABLE ORDERS(
ORDERID NUMBER(20) PRIMARY KEY,
QTY_SOLD NUMBER(10) CHECK(QTY_SOLD >0),
PRICE NUMBER(10,3),
ORDER_DATE DATE),
PRODID NUMBER(20) REFERENCES PRODUCTS(PRODID));